export const websitePages = [
  "PÁGINA INICIAL",
  "CARRINHO",
  "FERRAMENTA DE BUSCA",
  "LEGAL",
  "LISTA DE PRODUTOS DE UMA CATEGORIA",
  "PÁGINA DE CONFIRMAÇÃO",
  "PÁGINA DE DETALHES DO PRODUTO",
  "PÁGINAS DA CATEGORIA DE PRODUTOS",
  "RASTREAMENTO E RELATÓRIOS",
];
